server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: test
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms
    database: 3
  cache:
    type: redis