spring:
  r2dbc:
    #url: r2dbcs:mysql://localhost:3306/test?sslMode=DISABLED
    #url: r2dbcs:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&SSL=false&sslMode=DISABLED
    url: r2dbcs:mysql://127.0.0.1:3306/test?&SSL=false&sslMode=DISABLED&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    pool:
      enabled: true
      max-size: 10
      initial-size: 10
      validation-query: select 1
  jpa:
    show-sql: true
